#!/bin/bash -xe
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )
LIBS=$(echo ${DIR}/lib/*-linux-gnu*)
#LIBS=$LIBS:$(echo ${DIR}/usr/lib/*-linux-gnu*)
#LIBS=$LIBS:$(echo ${DIR}/usr/lib)
LIBS=$LIBS:${DIR}/usr/local/lib
export MAGICK_HOME=${DIR}/ImageMagick
export MAGICK_CODER_MODULE_PATH=$(echo ${DIR}/usr/lib/*-linux*/ImageMagick-*/modules-*)/coders
export MAGICK_CODER_FILTER_PATH=$(echo ${DIR}/usr/lib/*-linux*/ImageMagick-*/modules-*)/filters
export MAGIC=$DIR/usr/share/misc/magic
exec ${DIR}/lib*/ld-*.so* --library-path $LIBS ${DIR}/usr/local/bin/python3 "$@"
